In [11]:
%matplotlib inline
# OpenCV-Python utiliza NumPy para el manejo de imágenes
import numpy as np
# cv2 es el módulo python para acceder a OpenCV 
import cv2 as cv
# Usamos las poderosas herramientas de graficación de matplotlib para mostrar imágenes, perfiles, histogramas, etc
import matplotlib.pyplot as plt

In [12]:
def find_middle_point(coordinates):
    coordinates = coordinates[0]
    middle_points=[]
    while bool(coordinates.any()):
        search=coordinates[0]
        # print(coordinates)
        coordinates = np.delete(coordinates, 0, axis=0)
        objective=search[1]
        data=[]
        for i in coordinates[:,1]:
            i = int(i)
            i= abs(i-objective)
            data.append(i)
        # print(data, data.index(min(data)))
        middle_points.append((search[0:2]+coordinates[data.index(min(data))][0:2])/2)
        coordinates = np.delete(coordinates, data.index(min(data)), axis=0)
        # print(middle_points)
    return middle_points


In [13]:
# Leemos la imagen
#=================
img = cv.imread('TP3/eyes.jpg')
#img = cv.imread('eyes.jpg')
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

# Suavizamos la imagen
#=====================
gray = cv.medianBlur(gray,5)

# cv.imshow('tapitas',gray)
cv.waitKey(0)
cv.destroyAllWindows()


# Obtenemos los círculos por la transformada de Hough
# (imagen en grises, método, flag de resolución del acumulador, dist mín entre centros de círculos
# umbral alto de Canny, umbral del acumulador, radio_min, radio_max)
#===================================================================
img_out = img.copy()
# circles = cv.HoughCircles(gray,cv.HOUGH_GRADIENT,1,minDist=10,param1=120,param2=30,minRadius=25,maxRadius=42)
circles = cv.HoughCircles(gray,cv.HOUGH_GRADIENT,1,minDist=10,param1=120,param2=23,minRadius=27,maxRadius=42)


points=find_middle_point(circles)

for i in points:
    print(i[0],i[1])
    # Dibujamos el centro del círculo
    cv.circle(img_out,(int(i[0]),int(i[1])),2,(0,0,255),3)


circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # Dibujamos el círculo externo
    cv.circle(img_out,(i[0],i[1]),i[2],(0,255,0),2)
    # Dibujamos el centro del círculo
    cv.circle(img_out,(i[0],i[1]),2,(0,0,255),3)
cv.imshow('detected circles',img_out)
cv.waitKey(0)
cv.destroyAllWindows()


302.5 186.0
299.5 415.5
298.5 509.0
302.0 78.5
293.0 295.0


In [14]:
img_out = img.copy()
# circles = cv.HoughCircles(gray,cv.HOUGH_GRADIENT,1,minDist=10,param1=120,param2=30,minRadius=25,maxRadius=42)
circles = cv.HoughCircles(gray,cv.HOUGH_GRADIENT,1,minDist=10,param1=140,param2=17,minRadius=10,maxRadius=17)

circles = np.uint16(np.around(circles))
print(circles)

points=find_middle_point(circles)

for i in points:
    print(i[0],i[1])
    # Dibujamos el centro del círculo
    cv.circle(img_out,(int(i[0]),int(i[1])),2,(0,0,255),3)

for i in circles[0,:]:
    # Dibujamos el círculo externo
    cv.circle(img_out,(i[0],i[1]),i[2],(0,255,0),2)
    # Dibujamos el centro del círculo
    cv.circle(img_out,(i[0],i[1]),2,(0,0,255),3)
cv.imshow('detected circles',img_out)
cv.waitKey(0)
cv.destroyAllWindows()

[[[464 516  12]
  [454  80  12]
  [132 506  13]
  [150  80  11]
  [462 420  11]
  [136 414  12]
  [460 180  11]
  [144 188  10]
  [446 294  11]
  [138 294  11]]]
298.0 511.0
302.0 80.0
299.0 417.0
302.0 184.0
292.0 294.0
